#!/bin/bash

echo "🚀 ML Service Deployment to Render"
echo "=================================="
echo ""
echo "📋 Prerequisites:"
echo "1. Go to https://render.com and create an account"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository: https://github.com/VictorWu03/market-brief.git"
echo ""
echo "⚙️  Configuration Settings:"
echo "   Name: finance-ml-service"
echo "   Root Directory: ml-service"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "🔧 Environment Variables (if needed):"
echo "   PORT: (auto-set by Render)"
echo ""
echo "📁 Files being deployed:"
echo "   ✅ main.py - FastAPI application"
echo "   ✅ requirements.txt - Python dependencies"
echo "   ✅ Procfile - Deployment configuration"
echo "   ✅ models/ - ML model files"
echo ""
echo "🔗 After deployment:"
echo "1. Copy the Render URL (e.g., https://finance-ml-service.onrender.com)"
echo "2. Update src/lib/ml-prediction.ts with the new URL"
echo "3. Redeploy the frontend to Vercel"
echo ""
echo "✅ Ready to deploy!" 