services:
  - type: web
    name: finance-ml-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: ml-service
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7 